# Generated by Django 3.1.3 on 2020-11-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20201102_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_pic',
        ),
    ]
